Nick Project - Grocery analysis

In [2]:
import sqlite3
import pandas as pd
# Connect to the SQLite database
conn = sqlite3.connect('GroceryAnalysis')

# Create a cursor object to execute SQL queries
cursor = conn.cursor()

In [19]:
# Cell 1
query1 = """
CREATE TABLE IF NOT EXISTS month_mapping (
    month_code VARCHAR(3) PRIMARY KEY,
    month_name VARCHAR(255)
);
"""
cursor.execute(query1)
conn.commit()

In [5]:
# Cell 2
query2 = """
INSERT OR IGNORE INTO month_mapping (month_code, month_name) VALUES
    ('M01', 'January'),
    ('M02', 'February'),
    ('M03', 'March'),
    ('M04', 'April'),
    ('M05', 'May'),
    ('M06', 'June'),
    ('M07', 'July'),
    ('M08', 'August'),
    ('M09', 'September'),
    ('M10', 'October'),
    ('M11', 'November'),
    ('M12', 'December');
"""
cursor.execute(query2)
conn.commit()

In [6]:
# Cell 3
query3 = """
CREATE TABLE IF NOT EXISTS cleaned_grocery_data(
    product_id VARCHAR(255),
    product_name VARCHAR(255),
    year INT,
    month_name VARCHAR(255),
    price_usd FLOAT
);
"""
cursor.execute(query3)
conn.commit()

In [7]:
# Cell 4
query4 = """
INSERT INTO cleaned_grocery_data (product_id, year, month_name, price_usd)
SELECT
    Series_id AS product_id,
    Year AS year,
    Period AS month_name,
    Value AS price_usd
FROM
    grocery_data gd;
"""
cursor.execute(query4)
conn.commit()

In [8]:
# Cell 5
query5 = """
UPDATE cleaned_grocery_data
SET product_name = (
    SELECT product_name
    FROM product_mapping
    WHERE product_mapping.product_id = cleaned_grocery_data.product_id
)
WHERE cleaned_grocery_data.product_id IN (
    SELECT product_id
    FROM product_mapping
);
"""
cursor.execute(query5)
conn.commit()

In [9]:
# Cell 6
query6 = """
UPDATE cleaned_grocery_data
SET month_name = (
    SELECT month_name
    FROM month_mapping mm
    WHERE cleaned_grocery_data.month_name = mm.month_code
);
"""
cursor.execute(query6)
conn.commit()

In [14]:
# Drop the view if it exists
drop_query = "DROP VIEW IF EXISTS grocery_data_data;"
cursor.execute(drop_query)
conn.commit()

# Create the view
query7 = """
CREATE VIEW grocery_data_data AS
SELECT cgd.product_id, cgd.product_name, cgd.YEAR, mm.month_name, cgd.price_usd
FROM cleaned_grocery_data AS cgd
LEFT JOIN month_mapping AS mm ON cgd.month_name = mm.month_code;
"""
cursor.execute(query7)
conn.commit()

In [15]:
# Cell 8
query8 = """
SELECT * FROM grocery_data_data;
"""
df = pd.read_sql_query(query8, conn)
df.head()

      product_id product_name  year month_name  price_usd
0  APU0000704111        Bacon  1980       None       1.45
1  APU0000704111        Bacon  1980       None       1.41
2  APU0000704111        Bacon  1980       None       1.36
3  APU0000704111        Bacon  1980       None       1.32
4  APU0000704111        Bacon  1980       None       1.27

In [16]:
# Execute a query and fetch the result into a DataFrame
query = "SELECT * FROM cleaned_grocery_data"
df = pd.read_sql_query(query, conn)

# Display the DataFrame
df.head()

      product_id product_name  year month_name  price_usd  avg_price_per_year
0  APU0000704111        Bacon  1980       None       1.45                1.46
1  APU0000704111        Bacon  1980       None       1.41                1.46
2  APU0000704111        Bacon  1980       None       1.36                1.46
3  APU0000704111        Bacon  1980       None       1.32                1.46
4  APU0000704111        Bacon  1980       None       1.27                1.46